github: https://github.com/tranvietphuoc

stackoverflow: https://stackoverflow.com/users/10872420/tran-viet-phuoc

linkedin: https://www.linkedin.com/in/tranvietphuoc/

email: phuoctv.ut@gmail.com

resume: ../src/static/resume.pdf

profile_picture: ../src/static/pyo3.png

blog_title: Phuoc's blog
