github: https://github.com/tvph

stackoverflow: https://stackoverflow.com/users/10872420/tran-viet-phuoc

linkedin: https://www.linkedin.com/in/tranvietphuoc/

email: phuoctv.ut@gmail.com

resume: ../static/assets/resume.pdf

profile_picture: ../static/assets/pyo3.png

blog_title: Phuoc's blog
